### ISSUE TITLE
Missing file?

### ISSUE THREAD

**Issue by inseo** [mbrehin/capitaine-flemme#10]
The `check-staged-contents.js` isn't in the `pre-commit/` folder.
Is it an oversight? 🤔

**Comment by mbrehin** [comment]
@inseo Yes désolé j'ai fait une mise à jour sans clarifier la doc (et en plus je ne recevais pas les notifs de ce projet 😕). 
Du coup je viens de pusher avec une mise à jour complémentaire : le projet utilise un module npm que j'ai créé : [`git-precommit-checks`](https://www.npmjs.com/package/git-precommit-checks). 
Je n'ai cependant pas extrait sous forme de module npm la partie automatisation des SVG au commit. Si jamais des gens sont intéressés je prendrai probablement le temps de le faire.
